apiVersion: v1
kind: Pod
metadata:
  name: cal-pod
  labels:
    app: cal-app
spec:
  containers:
    - name: caliculator
      # image: 982424467695.dkr.ecr.ap-south-1.amazonaws.com/mycalapp-awar05
      image: thipparthiavinash/mycalapp-awar05
      ports:
        - containerPort: 8080