apiVersion: v1
kind: Pod
metadata:
  name: cal-pod
  labels:
    app: cal-app
spec:
  containers:
    - name: caliculator
      image: nginx
      envFrom:
      - configMapRef:
          name: db-config
