apiVersion: v1
kind: Pod
metadata:
  name: secret-access-pod
  labels:
    app: secret-access-pod
spec:
  containers:
    - name: caliculator
      image: busybox
      command: [ "sh", "-c", "echo $DB_PASSWORD; sleep 500"]
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD